apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "emapp.fullname" . }}-config
  labels:
    {{- include "emapp.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.app.config.profile | quote }}
  APP_PORT: {{ .Values.app.config.appPort | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.app.config.mysql.databaseUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.app.config.mysql.databaseUsername | quote }}
