apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.app.config.appPort | int }}
      targetPort: {{ .Values.app.config.appPort | int }}
      {{- if eq .Values.app.serviceType "NodePort" }}
      nodePort: {{ .Values.app.config.nodePort | int }}
      {{- end }}
  type: {{ .Values.app.serviceType }}