{{- if .Values.app.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "emapp.secretName" . }}
  labels:
    {{- include "emapp.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    {{- toYaml .Values.app.sealedSecret.encryptedData | nindent 4 }}
  template:
    metadata:
      name: {{ include "emapp.secretName" . }}
      labels:
        {{- include "emapp.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
