global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/mysql
  tag: 8.4.3-debian-12-r0

architecture: standalone

auth:
  rootPassword: ""
  username: ""
  password: ""
  database: ""

primary:
  service:
    type: ClusterIP
    ports:
      mysql: 3306

  persistence:
    enabled: true
    size: 5Gi
    accessModes:
      - ReadWriteOnce

metrics:
  enabled: false

networkPolicy:
  enabled: false

serviceAccount:
  create: true

rbac:
  create: true