app:

  image:
    repository: spridoloba/emapp
    tag: "1.0"
    pullPolicy: Always

  resources:
    requests:
      cpu:
      memory:
    limits:
      memory:

  autoscaling:
    metricServer:
      enabled: false
    minReplicas: 1
    maxReplicas: 5
    cpu:
      enabled: true
      averageUtilization: 70
    memory:
      enabled: true
      averageUtilization: 80

  config:
    appPort: "8080"
    nodePort: "30080"
    mysql:
      databaseUsername: ""
      databaseName: ""
      secretmapName: "mysql"
      secretPasswordName: "mysql-password"
      databaseUrl: "jdbc:mysql://mysql:3306/mysql?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  startupProbe:
    initialDelaySeconds: 35
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 2

  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 5

  livenessProbe:
    initialDelaySeconds: 0
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 5
